DROP TABLE IF EXISTS users cascade ;
DROP TABLE IF EXISTS messages cascade ;
DROP TABLE IF EXISTS chatrooms cascade ;
CREATE TABLE IF NOT EXISTS users (
                                     id bigint generated by default as identity primary key,
                                     email VARCHAR,
                                     password VARCHAR  DEFAULT 'default_password'
);
CREATE TABLE IF NOT EXISTS messages (
                                       id bigint generated by default as identity primary key,
                                       author bigint REFERENCES users(id) NOT NULL,
                                       room bigint REFERENCES chatrooms(id) NOT NULL,
                                       text TEXT NOT NULL,
                                       time TIMESTAMP NOT NULL
    );
CREATE TABLE IF NOT EXISTS chatrooms (
                                            id SERIAL PRIMARY KEY,
                                            name TEXT NOT NULL,
                                            ownerID INTEGER REFERENCES users(id) NOT NULL
);

SELECT * FROM users;
SELECT * FROM messages;
SELECT * FROM chatrooms;